powers_of_ten.pdf: powers_of_ten.tex
	pdflatex powers_of_ten.tex

clean:
	rm -f powers_of_ten.out
	rm -f powers_of_ten.log
	rm -f powers_of_ten.aux

distclean: clean
	rm -f powers_of_ten.pdf

.PHONY: all clean distclean
