fortran_refcard.pdf: fortran_refcard.tex
	pdflatex fortran_refcard.tex

clean:
	rm -f fortran_refcard.out
	rm -f fortran_refcard.log
	rm -f fortran_refcard.aux

distclean: clean
	rm -f fortran_refcard.pdf
